apiVersion: v1
kind: ReplicationController
metadata:
  name: twasr-backend
spec:
  replicas: 2
  selector:
    app: twasr
    role: backend
  template:
    metadata:
      labels:
        app: twasr
        role: backend
    spec:
      containers:
        -
          name: twasr
          image: tongda/twasr-backend
          ports:
            -
              containerPort: 80
          volumeMounts:
            -
              mountPath: /opt/models
              name: kaldi-model
      volumes:
        -
          name: kaldi-model
          rbd:
            monitors:
              - 10.18.6.1:6789
            pool: rbd
            image: kaldi_model
            user: admin
            secretRef:
              name: ceph-secret
            keyring: /etc/ceph/ceph.client.admin.keyring
            fsType: ext4
            readOnly: true
